#!/usr/bin/env bash

# shellcheck disable=2030,2031,2234

set -e -u -o pipefail

main() (
  for branch; do
    has main && continue

    if ! clean; then
      echo "* '$branch' is not clean"
      continue
    fi

    commit=$(head)
    (set -x; git -C "$branch" rebase main)

    [[ $(head) == "$commit" ]] && continue

    (set -x; git -C "$branch" push -f)
  done
)

head() (
  git -C "$branch" rev-parse HEAD
)

has() (
  git -C "$branch" merge-base --is-ancestor "$1" HEAD
)

clean() (
  [[ -z $(git -C "$branch" status --untracked-files=no --porcelain) ]]
)

main "$@"
