#!/usr/bin/env yaml-to-dockerfile

- from: ubuntu:20.04

- run:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y
      build-essential
      default-jre
      docbook-xsl
      ghostscript
      libexpat1-dev
      libxml-parser-perl
      libyaml-perl
      xsltproc

- run:
    apt-get install -y
      git
      silversearcher-ag
      tig
      tmux
      vim
